[package]
name = "crate_b"
version = "0.1.0"
authors = ["Camelid <camelidcamel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crate_a = { path = "../crate_a" }
